# Generated by Django 2.2.4 on 2020-07-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200708_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lambda',
            name='question',
            field=models.CharField(max_length=40, verbose_name='question'),
        ),
    ]
