# Generated by Django 2.2.4 on 2020-07-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lambda',
            old_name='question',
            new_name='nome',
        ),
    ]
