# Generated by Django 2.2.4 on 2020-07-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200708_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lambda',
            old_name='nome',
            new_name='question',
        ),
    ]
